export const fullSongList = [
  {
    id: "026a8525-27c4-4e7d-b23f-8538f53dd3d6",
    created_at: "2024-12-16 15:44:11.54044+00",
    song_title: "Vaso d'alabastro",
    lyrics:
      '{comment: "VERSO:"}\n[C] La sola cosa che di p[G]iù prezioso ho[D]\nÈ un vaso d alabastro[Em]\nLo rompo ai piedi tuoi[C]\n\nTu vali molto più\nDell’oro mio Gesù\nDei desideri miei\nLa gioia trovo in te\n\n{comment:"PRE-CORO:"}\nSpando il mio cuo[G/B]re davanti al Re[C]\nChe il[Em] suo sangue versò per me[D/F#]\n\n{comment:"CORO:"}\nEccomi Si[G]gnor[D]\nIo mi of[Em]fro a Te[C]\nPrendimi T[G]i do[D]\nOgni pa[Em]rte del mio cuore (Ges[C]ù)[G][D][Em][C]\n\n{comment:"VERSO2:"}\n\nLa vita è quello che di più prezioso ho\nLa metto ai piedi tuoi\nTu meriti di più\nC’è poca forza in me\nSon pochi i giorni miei\nMa li vivrò per te Gesù\nChe Ti desti per me\n\n{comment:"BRIDGE:"}\n[G]Santo santo\n[D]Tu sei santo\n[Em]Santo è il Si[D]gnor\n\n\n',
    author: "Gateway Worship",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "02feb268-140b-4331-a91d-28224e62c955",
    created_at: "2024-12-11 21:43:22.921227+00",
    song_title: "Amore inspiegabile",
    lyrics:
      "{comment: Verse 1:}\n[E]Amore inspiegabile\nLa vita hai dato sulla[C#m] croce\n[A]Mi hai reso Tu[E]o per sempre\n\n{comment: Verse 2:}\nCon grande misericordia\nHai dato tutto hai dato amore\nIl Tuo grande amore\n\n{comment: PRE-CORO:}\n[B]È tempo di  decidere [C#m]per c[A]hi vivo\n[B]Ti [C#m]loderò tutta la l[A]ode ti darò\n\n{comment: Chorus:}\n[E]Per Te, per Te Gesù io vivo\n[C#m]Solo a[A] Te la mia lode do\nTu[E]tta la lode ti darò\nA Te, a Te Gesù mi arrendo\nTi loderò, con tutto ciò che ho\nTutta la lode ti darò\n\n{comment: BRIDGE:}\n[C#m]Sono tuo Signore\n[F#m]Vivosolo per lod [A]are TE\n[E]Lodare [B]Te",
    author: "Hillsong",
    upload_key: "E",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "0481b7ac-ac2e-41e4-9b06-cc921e33c745",
    created_at: "2024-12-16 15:44:46.544024+00",
    song_title: "Vivere per grazie",
    lyrics:
      '{comment: VERSE:}\n[C]Crocifisso pe[D]r\nSalvar[Em]mi Per sempr[G]e\n[C]Grazie a t[D]e so la v[Em]erità\n\n[C]Liberato [D]da\nPaura[Em] Vergogn[G]a\n[C]Grazie a [D]te sono li[Em]bero\n\n{comment:"CORO:"}\n[C]Ci chiami a vivere per gra[G]zia\nA[D]d amarti e cerc[Em]arti\n[C]Ci chiami a viv[G]ere per te G[D]esù\n\n\n{comment:"BRIDGE:"}\n\nVoglio cono[Am]scerti Di pi[Em]ù sempre di [D]più',
    author: "Michael Bahn",
    upload_key: "C",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "0546d6dc-6d53-41ce-8adb-dd90dd7804cb",
    created_at: "2024-12-16 15:48:53.221368+00",
    song_title: "Yahweh si manifesterà",
    lyrics:
      "\nYahweh,[C] Rafa[D]\nElohi[G/B]m, Shaddai[Em]\nJireh, [C]Adonai[D]\nSe m[Em]anifestará",
    author: "Unknown",
    upload_key: "C",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "0d38d81e-6969-423e-972f-0e500d74b9b9",
    created_at: "2024-12-16 09:52:28.121063+00",
    song_title: "Lode al nome Tuo ",
    lyrics:
      '{comment: "VERSO 1:"}\n[A]Lode al nome Tu[E]o Quando[F#m] la Tua benign[D]ità\nScorre a[A]bbondante su [E]di me Lo[F#m]de al nome Tuo[D]\n[A]Lode al nome Tu[E]o Nella [F#m]terra più arid[D]a\nDove tu[A]tto sembra im[E]mobile Lod[F#m]e al nome Tu[D]o\n\n{comment:"PRE-CORO:"}\n[A]Tornerò a [E]lodarTi sempre, P[F#m]er ogni dono Tu[D]o\n[A]E quando s[E]cenderà la not[F#m]te, Sarò ancora l[D]ì\n\n{comment:"CORO:"}\nBenedetto[A] è il nome del [E]Signor\nL[F#m]ode al nome Tuo[D]\nBenedetto[A] è il nome del [E]Signor\nIl[F#m] glorioso nome[D] di Gesù\n\n{comment:"VERSO 2:"}\nLode al nome Tuo\nQuando il sole splende su di me\nTutto sembra incantevole\nLode al nome Tuo\n\n{comment:"VERSO 3:"}\nLode al nome Tuo\nQuando vengo davanti a Te\nCon il cuore triste e fragile\nLode al nome Tuo\n\n{comment:"BRIDGE:"}\nTu doni[A] e porti via[E]\nTu don[F#m]i e porti via[D]\n[A]Per sempre sceglierò  [E] \n[F#m]Di benedire Te[D]',
    author: "Matt Redman",
    upload_key: "A",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "0d7ffdab-7d2d-4348-8394-e096fa2486b0",
    created_at: "2024-12-16 12:15:43.313908+00",
    song_title: "Re del Cielo",
    lyrics:
      '\n{comment:"Intro:"}\n[F]\n\n{comment:"VERSO 1:"}\n[F]Gesù venga il tuo [C]regno\nLa tua volon[Dm]tà sia [Bb]fatta in [F]noi\n[F]Gesù Tu sei il più [C]grande \nTu sei il Sal[Dm]vatore [Bb]Il tuo amore è in [F]noi\n\n{comment:"CORO:"}\n[F]Re del cielo vieni\nRe del cielo vie[C]ni\nLa tua gloria è [Dm]qui\nLa tua luce è [Bb]qui\nRe del cielo[F]\n[F]Re del cielo vieni \nRe del cielo vie[C]ni \nIl tuo nome [Dm]è infallibi[Bb]le \nRe del cielo[F]\n\n{comment:"VERSO 2:"}\nSiamo figli della grazia\nDella tua salvezza, grazie \nGesù porta i nostri cuori\nA guardare in alto verso Te\n\n\n{comment: INTERLUDE:}\n[ F C Dm Bb ]\nOh oh oh oh oh                    Oh oh oh oh oh\n\n{comment:"BRIDGE:"}\n[F]Re del cielo sei, Re[C] de[Dm]l cielo sei....[Bb]\n',
    author: "Paul Baloche",
    upload_key: "C",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "11ddb67e-4ec7-409a-b8c5-df49095378c1",
    created_at: "2024-12-16 12:02:49.875925+00",
    song_title: "Potente a salvar",
    lyrics:
      '{comment: "VERSO 1:"}\n[D]Tutti abbiam biso[A]gno\nDel Tuo infinito amor[F#m]e\nLa graz[E]ia Tua in[D] me\n[D]E noi ti ringraziam[A]o\nPer il Tuo sacrifi[F#m]cio\nPer no[E]i sulla croce[D][E][D][E]\n\n{comment:"CORO:"}\n[A]Gesù muove le mon[E]tagne\n[D]Dio è potente[A] a Salvar È[F#m] potente [E]a Salvar\n   \nPer sempre dona la salvezza \nGesù la morte schiacciò e vittoria donò\n\n{comment:"VERSO 2:"}\nNonostante i miei errori\nMi hai preso così come sono\nDonandomi pace e amor\nOra non posso fare altro\nche donare la mia vita\nAl Dio che mi salvò\n\n{comment:"BRIDGE:"}\n[D]La Tua luce si[A]a sul mondo si!  Canta![E]\n[D]Per la gloria [A]del risorto Re Gesù![E]\n[D]La Tua luce si[A]a sul mondo si! Canta![E]\n[D]Per la gloria [A]del risorto Re[E]',
    author: "Hillsong",
    upload_key: "A",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "13fb9f07-4d37-4b5b-be3c-cbb5c688f78f",
    created_at: "2024-12-16 15:46:31.82766+00",
    song_title: "Vivere per te",
    lyrics:
      '{comment: VERSE:}\n[B]Seguirò...La strada stretta\nCanterò..[G#m].un canto nuovo a Te\n[E]Mi alzerò...anche se sarò solo\n[B]Gr[G#m]iderò...mio Dio grande tu [F#/A#]sei\n\n{comment: CHORUS:}\n[B]Gesù voglio vivere per Te\n[G#m]Camminare nella verità\n[E]Dire a tutti chi [F#]Tu sei per me[B]\n[B]Guardo al premio ch e davanti a me\n[G#m]Lascio ogni cosa inutile\n[E]Gesu voglio vive[F#]re per te[B][C#m7]\n\n{comment:"BRIDGE:"}\nIo ho deciso[B] di seguire Cristo\nIo ho deciso[E] di seguire Cris[B]to\nIo ho deci[B]so di seguire Cristo[G#m7]\nIndietro no,[E] [F#] non tornerò[B]\n\nSe ness[B]un viene con me, ancor lo seguirò\nSe ness[E]un viene con me, ancor lo seguirò[B]\nSe ness[B]un viene con me, ancor lo seguirò[G#m7]\nIndietro n[Ema7]o, [F#] non tornerò[G#m7]![F#/A#]\nIndietro n[Ema7]o, [F#] non tornerò[G#m7]![F#/A#]\nIndietro n[Ema7]o, [F#] non[G#m7] torn[F#/A#]e---rò[F#/A#]!- (CORO)',
    author: "Michael Bahn",
    upload_key: "B",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "13fd54c7-8b1b-4e65-8aea-1467fb99c96d",
    created_at: "2024-12-16 10:18:02.873088+00",
    song_title: "Maestà",
    lyrics:
      '\n{comment:"VERSO 1:"}\n[Em]Sono[D] q[C]ui, u[Bm]milmente vengo a te[C]\n[Bm]Coprimi con la grazia T[Am]ua[Bm]\n[Em]Sono[D] qu[C]i, Er[Bm]o schiavo senza Te[C]\n[Bm]Tu mi hai dato la liber[Am]tà [Bm]\n\n{comment:"PRE-CORO:"}\n[Em]Tro[D]ve[G]rò il vero amore [Em]sol[D]o [G]in Te\nPerché per primo [A]Tu hai amato me[C][D][C][D]\n\n{comment:"CORO:"}\n[G]Maes[D]tà , [Em]maest[C]à \nTi [G]dono tutto quello che h[D]o\nDal[Em]le tue mani vita riceve[C]rò\n\n{comment:"VERSO 2:"}\nSono  qui, il perdono ho avuto in Te  \nPerdono anch\'io chi mi ferirà\nResto qui, so che sei vicino a me  \nIl Tuo fuoco mi santificherà\n\n{comment:"CORO 2:"}\n[G]Maes[D]tà , [Em]maest[C]à \nPer[G] sempre canterò del tuo am[D]or\nIn [Em]presenza della tua maes[C]tà',
    author: "Martin Smith",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "15bf3c11-3d69-4428-aed3-2fddf3ea5a9d",
    created_at: "2024-12-15 21:51:26.20952+00",
    song_title: "Gesù ti amo",
    lyrics:
      "\n{comment: Chorus:}\nIl tuo nome è m[G]iele su[A]lle mie labb[D]ra\nIl tuo spirito è[G] come l[A] acqua del f[D]iume\nLa tua parola è una [G]lampa[A]da ai miei pied[Bm]i\nGesu ti a[G]mo\nTi a[A]mo\n\n{comment: Verso 1:}\n[G]Santo San[C]to\n[Em]Risorto [D]e innalza[C]to\n[G]San[D]to[G]\n\n{comment: Verso 2: }\n[G]Santo San[C]to\n[Em]Tre volt[D]e santo s[C]ei\n[G]San[D]to[G]",
    author: "Fernando Coeriel",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "17e86227-6126-4e08-bda0-c0c1fe514456",
    created_at: "2024-12-16 15:48:11.677287+00",
    song_title: "Way Maker",
    lyrics:
      '{comment: "Verso"}\nTu[A] sei qui, Ti muov[E]i tra di noi\nAdoro te [B]adoro te[C#m]\nTu [A]sei qui, operi tr[E]a noi\nAdoro te a[B]doro te[C#m]\n\n{comment:"Coro"}\nFede[A]le, miracoloso\nSei [E]potente, luce nel buio[B]\nSei Tu che aprirai una via (x[C#m]2)\n\n{comment:"Verso"}\nTu sei qu[A]i, tocca il cuore[E] mio\nAdoro te [B]adoro te[C#m]\nTu [A]sei qui, guarisci[E]mi Signor\nAdoro te a[B]doro te[C#m]\n\n{comment:"Coro"}\n[A]Fedele, miracoloso\n[E]Sei potente, luce nel buio[B]\nSei Tu [C#m]che aprirai una via (x2)\nEcco chi Tu sei[A]\nEcco chi Tu sei[E]\nEcco chi Tu sei[B]\nEcco chi Tu sei[C#m]\n\n{comment:"Bridge"}\nA[A]nche quando non riesco a sentirti\n[E]Credo che Tu continui a guidarmi\nAprirai\nAprirai\nAprirai\nApri una via\n',
    author: "Sinach",
    upload_key: "A",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "1daf60b2-028a-445d-ad3d-ea4c59e658a3",
    created_at: "2024-12-16 12:37:20.406048+00",
    song_title: "Ti do gloria",
    lyrics:
      '{comment: "Intro"}\n\n[C][G][Am][F]\n\n{comment:"Verso"}\n[C]QUANTO BELLO SEI TU GESÙ[G]\n[Am]LE TUE PAROLE ED IL TUO AMORE[F]\n[C]QUANTO GLORIOSO SEI TU GESU\n\n{comment:"Precoro"}\n[Am]E IL T[F]UO POT[G]ER, [F]FU LA TUA CROCE\n[C]QUELLA CHE[G] MI SALVO, MI RISCATTO\n[Am]E IN U[F]N MOMENTO LÌ CI DONÒ LIBERTÀ\n\n{comment:"Coro"}\n[C]TI DO GLORIA, GLORIA\n[G]TI DO GLORIA, GLORIA\n[Am]TI DO GLORIA, GLORIA\n[F]A TE GESU\n\n\n{comment:"Bridge"}\n[F]CON UNA[G] CORONA DI SPINE\n[Am]DIVENT[C]ASTI RE PER SEMPRE',
    author: "ANDRÉS SPYKER",
    upload_key: "C",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "1e51a419-0359-4080-bd39-7ed5756f429f",
    created_at: "2024-12-11 21:22:00.466616+00",
    song_title: "Cornerstone",
    lyrics:
      "{comment: Verse 1:}\n[B]La mia speranza è solo in Te\n[E]Nella giustizia e il sangue t[F#]uo\n[G#m]Ed ora in poi fiducia a[F#]vrò\n[E]Solo nel [F#]nome di Ge[B]sù\n\n{comment: Chorus:}\n[B]Cris[E]to è [G#m]forza in [F#]me\n[B]Rocc[E]ia su[G#m] cui cost[F#]ruirò\n[B]Nell[E]a pro[G#m]va Lui è [F#]il Re\nI[B]l Re dei re\n\n{comment: Instrumental: G#m   E   F#}\n\n{comment: Verse 2:}\n[B]E quando il buio è intorno a me\n[E]La grazia sua non cambi[F#]erà\n[G#m]E nelle mie difficol[F#]tà\n[E]Saldo sta[F#]rò sul mio Ge[B]sù\n[E]Saldo sta[F#]rò sul mio Ge[B]sù\n\n{comment: Verse 3:}\n[B]Quando la tromba suonerà\n[E]Sarò trovato in Ge[F#]sù\n[G#m]Vestito della grazia s[F#]ua\n[E]Davanti[F#] al trono io st[B]arò\n",
    author: "Hillsong",
    upload_key: "B",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "204bf510-0b9d-4a56-8371-c773cfeeafc5",
    created_at: "2025-02-06 19:42:31.896557+00",
    song_title: "Questa è la grazia tua",
    lyrics:
      '\n{comment:"VERSO:"}\n[G]chi vince il buio ed il peccato\n[C]il cui amore è così grande\n[Em]il Re di gloria, Re [D]sopra tutti i r[C]e\n\nchi scuote tutta la terra intera \nchi ci stupisce in ogni istante\nil Re di glora, Re sopra tutti i re \n\n{comment:"CORO:"}\nquesta è la grazia Tu[G]a\nil Tuo infinito amor[C]e\nhai preso il posto [Em]mio\nportato i pesi mi[D]ei\nhai dato la tua vi[G]ta\nperché io fossi libe[C]ro[Em]\nGesù io ca[D]nto\ndi quel che fai per [G]me [C]\n\n{comment:"VERSO 2:"}\n\nchi spazza via la confusione\nchi ci ha resi suoi figli e figlie\nil Re di gloria, Re sopra tutti i re\nchi guida il mondo con la giustizia\nil cui splendore è come il sole\nil Re di gloria, Re sopra tutti I re\n\n{comment:"BRIDGE:"}\nG  (Em)   \nDegno è l agnello di Dio \n[C]Degno è il re che ha vinto la morte\n',
    author: "Phil Wickham",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "2595a9c2-5b10-4a90-8499-ccd37d89e0b0",
    created_at: "2024-12-11 21:44:38.239518+00",
    song_title: "Ecco l'uomo che soffrì ",
    lyrics:
      "{comment: Verse 1:}\n[E]Ecco l’uomo che soffr[A]ì umil[E]iato fu[A][E][B]\n[C#m]Le mie colpe su[A] di[C#m] se, por[A]tò per me [B]Gesù[E]\n\n{comment: Verse 2:}\n[E]Il silenzio sopportò,[A] le sp[E]ine ed [A]il dolor[E][B]\n[C#m]“Sia fatta la tua vol[A]ont[C#m]à”, al Padre Lu[A]i pregò[B][E]\n\n{comment: Chorus:}\nSulla cr[C#m]oce Tu [A]mi salvasti[E][B]\nDimostra[C#m]ndo li [A]il tuo amor[B]\nIl mio cuore c[A]anta all[E]eluia[B][C#m]\nGl[A]oria e[B] onore a [E]Te Signor\n\n{comment: Verse 3:}\nUnigenito di Dio\nIl mondo riscattò\nPer donarlo anche a chi\nSul legno Lo inchiodò\n\n{comment: BRIDGE:}\nLui pa[C#m]gò per me [A]ogni de[E]bit[B]o\nCon il[C#m] sangue ch[A]e per m[E]e Lui ve[B]rsò\nE ness[C#m]uno mai mi[A] condan[E]ner[B]à\n Perch[C#m]è in Gesù [A]ho la l[E]ibe[B]rtà\n\n{comment: Verse 4:}\nSulla morte trionfò, la tomba è vuota ormai\nAlleluia al Salvator, Gesù risuscitò",
    author: "Hillsong",
    upload_key: "E",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "2fd7f18e-0df1-4943-b8bb-92304376b5a0",
    created_at: "2024-12-16 12:31:59.895215+00",
    song_title: "Seguire Te",
    lyrics:
      '\n{comment: VERSE:}\nTu ci[G] hai chiamato ad unirci a Te\nLa[Em]sciare tutto quanto dietro e… Seguire[C] T[G]e\nA ri[G]nunciare a noi stessi\nP[Em]rendere la nostra croce e… Seguire [C]Te[G]\n\n{comment: CHORUS:}\nNoi seg[C]uiremo [G]Te, Gesù[D][Em]\nTu sei[C] la ver[G]ità[D]\nViviam[C]o per il R[G]e\nE la nos[D]tra casa è in cie[Em]l\nNoi seg[C]uiremo[Em] Te, Ge[D]sù[G]\n\n{comment:"BRIDGE:"}\n[A]Noi vogliamo Te, Noi voglia[C]mo Te\nNon il mond[G]o, non il mondo\n[A]Noi vogliamo Te, Noi voglia[C]mo Te\nNon il mond[G]o, non il mondo, solo [Em]Te Si[D]gnor[C]',
    author: "Michael Bahn",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "33e3cfe6-886f-4e47-aab6-f1120dc42c17",
    created_at: "2024-12-16 12:36:18.337727+00",
    song_title: "La benedizione - The blessing",
    lyrics:
      "\nDio ti protegga, ti benedica\nChe risplenda il Suo volto\nE la Sua grazia su di Te\nTi rivolga il Suo sguardo\nE sia pace in Te\n\nAmen, amen, amen\n\nSu di Te sia il Suo favore\nE per mille generazioni\nSia su tutta la famiglia\nE su i figli dei tuoi figli\n\nSia con te la Sua presenza\nTi preceda e ti segua\nChe ti riempia, ti circondi\nÈ con te Lui, è con te Lui\n\nAl mattino e alla sera\nNel tuo andare, nel tornare\nNel tuo pianto, nella gioia\nÈ per te Lui, è per te Lui",
    author: "Kary Jobe",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "39b135a6-2531-4873-a5c2-2b325ab6351d",
    created_at: "2024-12-16 09:51:02.088796+00",
    song_title: "Leone e l'agnello",
    lyrics:
      '{comment: "Verso 1"}\n[G]Sulle nuvole verrai\nI re si inchineranno a Te[C]\n[Em]Ci libererai quan[D]do noi ti loderem[C]\nChi fermerà l’onnipotente[D]\n\n{comment:"Coro"}\n[G]Tu sei il leone, leone di giuda[Em]\nRuggisci in potenza Combatti per noi [C]\nOgni ginocchio a te si piegherà[D][G]\n[G]Oh Tu sei l’agnello, l’agnello immolato[Em]\nHai vinto e spezzato, le catene del peccato[C]\nOgni ginocchio a te si piegherà[D][G]\nOgni ginocchio a te si piegherà[D][G]\n\n{comment:"Verso 2"}\n[G]Oh porte apritevi il re di gloria fate entrar[C]\n[Em]Salvezza porterà e vivrem la libe[D]rtà[C]\nChi fermerà l’onnipotente[D]\n\n{comment:"Special"}\n[Am]Chi fermerà l’onnipotente[G/B]\n[C]Chi fermerà l’onnipotente[D]\n',
    author: "Leeland",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "3ccc3677-25e3-4ef2-a63c-902f4684f574",
    created_at: "2024-12-15 22:12:46.89152+00",
    song_title: "Gratitudine",
    lyrics:
      "{comment: Verso}\nE come[B] potrei con parole mie [G#m]\nDimostrarti[F#] la mia gratit[E]udine \nCanto una ca[B]nzone come ho fatto già[G#m]\nChe poi finir[F#]à ma il tuo amore no [E]\n\n{comment: Coro}\nE alzo le m[B]ie mani e ti lodo ancora e ancora [F#]\nPerché tutto ciò che ho è Alleluia allelui[E]a[G#m][F#]\nE so ch[B]e non è molto ma cosa potrei dire a un re [F#]\nOltre a un canto nel cuore Alleluia allelu[E]ia [G#m][F#]\n\n{comment: Verso 2}\nUna cosa[B] so e quella farò [G#m]\nApro le mi[F#]e braccia e adoro te [E]\n\n{comment: Bridge}\nOh ani[B]ma mia non essere timida innalza il tuo canto[F#]\nPerché dentro di te dimora un leone [E]alzati e lodalo [B][F#]\nOh ani[B]ma mia non essere timida innalza il tuo canto[F#]\nPerché dentro di te dimora un leone [E]alzati e lodalo[G#m][F#]",
    author: "Brandon Lake",
    upload_key: "B",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "3d54344f-0d3b-42df-9fb1-506faac2194e",
    created_at: "2024-12-15 21:55:55.398927+00",
    song_title: "Gioia nel mondo - Joy to the world",
    lyrics:
      "{comment: Verse 1:}\nG[G]ioia nel mondo è nato il[C] re[D][Em]\nIl mond[C]o accolga[D] Lui[Em]\nChe o[G]gni creatura\nP[G]roclami il suo nome\nLa te[C]rra canta per Lui\nIl c[D]ielo canta per Lui\nLa[C] terra e il[Em] cielo cant[D]eran[G]\n\n{comment: Chorus:}\nCanteremo[G] a Lui\nGioia nel mo[G]ndo\n\n{comment: Verso 2:}\nI[G]l salvatore[C] regn[D]erà[Em]\n con gr[C]azia ed a[D]mor[Em]\nLa gl[G]oria della\n[G]Sua giustizia \nTutta[C] la terra vedrà\nTutt[D]a la terra vedrà\nLa[C] sua grande[Em]zza ognuno [D]vedrà[G]\n\n{comment: Bridge}\nC[G]on grande Gioia ti adoriamo[D]\nD[Em]io di gloria ed amor[C]\nC[G]ome i fiori i nostri c[D]uori\nS[C]ia aprono davanti a[D] te[G]",
    author: "Phill Wickam",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "3e089664-fec0-4bb9-a082-4c16a466d64d",
    created_at: "2024-12-16 09:54:02.971638+00",
    song_title: "Luogo più alto",
    lyrics:
      '{comment: "Verso"}\nAi tuoi piedi b[G]rucia il mio cuor[D]\nAi tuoi piedi[Em] do tutto ciò che sono[C]\nQuesto è il luo[G]go della mia libertà[D]\nDove nessuno [Em]mi può giudicar[C]\n\n{comment:"Pre-Coro"}\nMi hai perdonato, mi ha[C]i portato alla tua presenza[D]\nMi hai rialzato, ora[Em] mi prostro ad adorarti[D]\n\n{comment:"Coro"}\nNon c’è luogo più alto, più gra[C]nde [D]\nche stare ai piedi tuoi, st[Em]are ai piedi tuoi [D]\nNon c’è luogo più alto, più gra[C]nde [D]\nche stare ai piedi tuoi, st[Em]are ai piedi tuoi [D]\n\n{comment:"Bridge"}\nEd è qui c[C]he io resterò, [D]prostrato ai pie[G]di[D/F#] tuoi [Em]\nEd è qui c[C]he io resterò a[D]i tuoi piedi Cri[G]stoooo',
    author: "Miel San Marcos",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "3efcea1f-2f15-4c2c-98cc-55b3f6ec224b",
    created_at: "2024-12-16 09:52:56.438428+00",
    song_title: "Lode offriamo a te",
    lyrics:
      '{comment:"VERSO:"}\n[G]non c’è nessu[C]no in terra o in cielo\n[G]degno di lode c[C]ome Te\n[G]alziamo insiem[C]e le nostre voci\n[Em]per innalzare[C] solo Te\n\n{comment:"CORO:"}\n[G]Lode lode noi offriam[C]o a Te\n[G]Sei la via e la ve[C]rità\n[Em]lode lode noi of[C]friamo [G]a Te Gesù\n \n{comment:"VERSO 2:"}\ni nostri cuori chinati e arresi\nnoi ci prostriamo ai piedi tuoi\ncon Te soltanto vogliamo stare\nper sempre canteremo noi\n\n{comment:"BRIDGE:"}\nl[C]\'amore Tuo ci s[D]osterrà\nt[Em]u regni tra noi\n[C]ora siamo i tuoi\n',
    author: "Michael Bahn",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "40486453-8d94-4edc-afea-d1274b54e85a",
    created_at: "2024-12-16 09:30:15.921195+00",
    song_title: "Il nome di Gesù",
    lyrics:
      '{comment: "Verso"}\n[C#m]Tra le tue br[A]accia io mi[E] consegner[B]ò\n[C#m]Le paure io l[A]ascio sull\'[E]altare[B]\n[C#m]E tutti i pia[A]ni miei ogg[E]i li do a [B]Te\n[C#m]Prendi il tuo[A] posto Dio [E]sei benven[B]uto qui\n\n{comment:"Pre-Coro"}\n[A]E su di noi manda la pioggia si su di noi[C#m]\n[B]In tua presenza io mi prostre[A]rò\n[E]E dichiarerò che sei santo Dio[B]\n\n{comment:"Coro"}\nIl su[A]ono del cielo posso sentire\nS[C#m]offia il tuo vento soave su n[B]oi\n[A]Dichiarerò l\'unico nome che salva[E][B]\n[C#m]Gesù[A][E][B]\n[A]Il nome di [C#m]Gesù il nome di Ge[B]sù',
    author: "Unknown",
    upload_key: "E",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "436dbf09-e8d4-4da7-a5e8-82b37a7444b4",
    created_at: "2024-12-16 12:05:19.136067+00",
    song_title: "Questa casa è tua",
    lyrics:
      '{comment: "Verso 1"}\n[G]Tu sei il benvenuto qui la casa è Tua entra[C]\nIo mi svuoto di me Io mi[G/B] svuoto di me[C]\nSoffia il Tuo vent[G]o qui Prendi il Tuo trono reg[C]na in noi\nNoi vogliamo Te Noi vogl[G/B]iamo Te[C]\n\n{comment:"Coro"}\nE Questa ca[C]sa è Tua e noi\nLa consegniamo totalmente a T[D]e Gesù[Em][D]\nsi qu[C]esta casa è Tua e noi\nLa consegniamo totalmente a[D] Te Gesù[Em][D]\n\n{comment:"Special"}\nSii innalzato c[C]he il Tuo nome Cresca[Am]\nRiempici di Te [G]Riempici di Te[D]\nSii innalzato c[C]he il Tuo nome Cresca[Am]\nVieni e infuoca[G]mi si vieni e infuocami[D]',
    author: "Chevin Rubio Invencible Band",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "45b45991-29aa-43e1-af2e-82ca65efdb27",
    created_at: "2025-05-10 13:43:39.87362+00",
    song_title: "Dichiaro Gesù - I speak Jesus ",
    lyrics:
      "{comment:Intro:} \n[C] [Am] [F]\n{comment:Verso 1:}\n[C]Io dichiaro il nome di Gesù \n[Am]Sopra ogni mente ed ogni cuore \n[F]Perché è la sua presenza che dà pace \nDichiaro Gesù[C]\n{comment:Verso 2:}\n[C]Io dichiaro il nome di Gesù \n[Am]Su ogni dipendenza in mezzo a noi\n[F]Perché in lui c’è speranza e libertà \n[Dm]Dichiaro Gesù[C] \n{comment:Coro:}\nNome pote[G]nte che mi gua[F]risce\n[C]Vita per me\nRompe ca[G]tene,\n[F]splende nel buio \ne [C]brucia in me \n{comment:Verso 3:}\n[C]Io dichiaro il nome di Gesù \n[Am]Sopra ogni paura ed ansietà \n[F]Sui prigionieri della depressione[Dm] \nDichiaro Gesù[C] \n{comment: Bridge:}\n[C]Gesù grido il tuo nome \nSui monti[C7] e per le st[C]rade \n[Am]Gesù sopra le tenebre \n[Am9]E su ogni mio [Am]gigante \n[F]E sulla mia famiglia \n[Dm]Dichiaro il santo nome di Gesù [C]\n",
    author: "Charity Gayle ",
    upload_key: "C",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: NaN,
  },
  {
    id: "4631aa12-82d2-4812-a368-9aa8d4d0011a",
    created_at: "2024-12-16 15:49:55.840522+00",
    song_title: "Yeshua",
    lyrics:
      "Il mio orgogli[C]o mi strappò dal giardino[D]\nLa tua umiltà lo[C] riportò di nuovo a me[D]\nSe vendessi ciò c[C]he possiedo\nIn cambio dell'[D]amore fallirei[Em]\n\nPerchè l'amore no[C]n si compra\nNe lo si[D] merita\nL'amore è[C] un regalo\nPer grazia si ric[D]eve\n\nlo Voglio c[C]onoscerti Gesù[D]\nvogli[C]o conoscerti Gesù[D]\nDimorare in te[C]\nYeshu[C]a[D][Em][D]\n\nIl [C]mio amato è il più bello[Am]\nTra mi[G]gliaia di migliia[D]",
    author: "Alessandro Vilas Boas.",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "47b5822f-49cd-4b3b-8722-02fc2aa29ccb",
    created_at: "2024-12-15 22:10:30.828099+00",
    song_title: "Glorioso Giorno",
    lyrics:
      "{comment: Verso 1}\n[G]Respiravo ma non vive[C]vo[G]\nE nascondevo og[Em]ni mio errore\nlo ero morto ma h[C]o incontrato te[G]\n\n{comment: Verso 2}\n[G]Hai preso ogni mio pe[C]so su di te[G]\nCancellando ogn[Em]i mio errore\nlo ero morto ma ho i[C]ncontrato te[G]\n\n{comment: Coro}\nTu mi hai chiamato, E so[G]no corso da [C]te[G]\nGlorioso è il giorno [C], In cui sei morto per me [G]\nTu mi hai chiamato, E so[G]no corso da [C]te[Em]\nGlorioso è il giorno [C], In cui sei morto per me [G]\n\n{comment: Verso 3}\n[G]La libertà ho trovato[C] in te[G]\nLe cose vecchie son[Em]o passate\nlo ero morto ma adesso[C] vivo in te[G]\n\n{comment: Bridge}\n[G]Ero legato dal mio peccato\n[G]Tu mi hai salvato e sono stato perdonato\n[G]lo ero solo senza riparo\n[G]E mi hai chiamato cittadino del cielo\n[G]Ero ferito, Tu mi hai guarito\nÈ nel tuo amore che io ora respiro\n[Em]adesso vedo in te u[D]n futuro\nPerché hai chiamato me e Sono corso[C] da te[G]",
    author: "Passion",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "4a417dda-9c0d-4ac4-bd47-e5f49ecd0ec2",
    created_at: "2024-12-11 21:01:32.741884+00",
    song_title: "Ancora lo rifarai",
    lyrics:
      "{comment: Intro:}\n[C][G/B]\n\n{comment: Verse1}\n[C] Io pensavo che\n[G/B] Le mura cadessero\n[C] Ma Tu non mi hai deluso mai[G][|][G]\n[C] L'attesa finirà\n[G/B] So che Tu hai vinto già\n[C] Tu non mi hai deluso mai[G][|][G]\n\n{comment: Chorus}\n[C/E]Confiderò in Te[D/F#]\nLa promessa si adempirà, Tu[G] sei fedele[C]\n[C/E]Sicuro in Te[D/F#]\n                     G             C          (G/B)\nPer sempre resterò, Tu sei fedele\n\n{comment: INSTRUMENTAL:}\n[G/B][C]\n\n{comment: VERSE 2}\nLa notte finirà\nLa tua parola si compirà\nPer sempre io Ti loderò\nGesù Tu sei il mio re\nCoprimi col tuo amore\nPer sempre io Ti loderò\n\n\n{comment: BRIDGE}\n[C] Ti ho visto già  [G/B][C]\n[C] muover montagne[D/F#]\n[G] E so che Tu   [D/F#] a[G]ncora lo r[G/B]ifarai[C]\n[C] Apri una via   [G/B] d[C]ove non c'era[D/F#]\n[G] E so che Tu  [D/F#] an[G]cora lo ri[G/B]farai[C]",
    author: "Elevation Worship",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "4e8f66be-7e21-4d11-b353-3cab4f653066",
    created_at: "2024-12-11 21:02:32.229956+00",
    song_title: "Apri i miei occhi Signore",
    lyrics:
      "{comment: Verse 1:}\n[C]Apri i miei occhi Signore\n[G/B]Apri i miei occhi Signor\nVoglio vederti[F], voglio vedert[C]i\n\n{comment: Chorus:}\nVederti splendere [G]Signor[Am7]\nN[F]ella luce della Tua gloria[Gsus]\n[G]Versa il Tuo amore su noi[Am7]\nMentre cantiamo San[Dm7]to Santo  (Ripetere[Gsus] da capo)\n\n{comment: Bridge X2}\n[C]Santo Santo Santo\n[G/B]Santo Santo Santo\n[F]Santo Santo Santo[Dm]\nVoglio vederti![C]",
    author: "Michael W. Smith",
    upload_key: "C",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "5c8e2a68-81ff-4b97-b53a-e70cd649d876",
    created_at: "2024-12-16 10:24:23.169606+00",
    song_title: "Non c'è niente",
    lyrics:
      '{comment:"Intro:"}\n[G][C/G][G]\n{comment:"Verso 1"}\n[C]Pensavo che[G] potesse [C]riempirmi[G]\nCiò che dà il mondo[Em]\nFama e oro non [D]bastano mai[C]\n\n{comment:"Verso 2"}\nPoi arrivi Tu che mi riporti indietro\nE ciò che cercavo\nLo troverò qui\nQui nel tuo amor\n\n{comment:"Coro"}\nNon c\'è niente,[G] meglio di Te\nNessuno,[Em] meglio di Te\nNon c\'è niente[C]\nNiente é meglio di Te[G]\n\n{comment:"Verso 3"}\nNon ho paura di mostrarti i miei errori\nSai tutto di me\nMi conosci ma non mi abbandonerai\n\n{comment:Verso 4}\nPerché il Dio sul monte\nÉ il Dio nella valle\nNon c\'è posto in cui\nNon mi troverai\nTu sei sempre con me\n\n{comment: Instrumental:}\n[G][C][G][C]\n{comment:"Bridge"}\n[G] Cambi il lutto in gioia[C][G]\nLa vergogna in gloria[C][G]\nIl peccato in perdono[C]\nTu sei l\'unico [Em]che p[C]uò[G]\n\nPorti vita alla morte\nRendi giusto il mio cuore\nLe ossa secche in soldati\nTu sei l\'unico che può',
    author: "Elevation Worship",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "61e54e53-caff-4ca3-980f-d11b4e2965e3",
    created_at: "2024-12-11 21:15:02.125411+00",
    song_title: "Per far entrare il Re",
    lyrics:
      "{comment: Verse 1}\n[Em]Per fare entrare il Re Gesù il [C]Re di Gloria[G]\nlo apro il mio cuore a[D/F#]pro il mio cuore[Em]\n\n{comment: Verse 2}\n[Em]Chi è il Re di Gloria chi è i[C]l Re di Gloria\n[G]Gesù Gesù Lui è i[D/F#]l Re, Lui è il Re\n\n",
    author: "MORADA",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "62c64dc5-d16e-495d-b50c-df16f6563c7f",
    created_at: "2024-12-11 21:25:35.052221+00",
    song_title: "Cuore stabile",
    lyrics:
      "{comment: Verse 1:}\n[G]Anche se non vedo cosa ce\nDavanti a me io[Em]\nDi Te mi fide[C]rò\n\n{comment: Chorus:}\ndammi un cuore che n[G]on cede\ndammi un cuore che non teme\nQui con te[Em]\ndammi un cuore che[C] perdona\nUna fede [D]che continua\nA [G]credere\n\n{comment: Verse 2:}\nÈ buio intorno[G] a me, il vento è forte ma\nTu non mi lasci    [Em] Tu non mi lasci[C]\n\n[G]La notte è lunga ma, il giorno arriverà\nLa tua l[Em]uce in me, mi sta camb[C]iando\n\n{comment: Bridge:}\n[C]Tu sei fedele e non mi las[D]ci\nSei un Dio fedele e Tu mi po[Em]rti\nOltre tutti i miei limiti[G/B]\n\n\n",
    author: NaN,
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "65622af4-00b7-482d-8f4a-69cd4c4a8c63",
    created_at: "2024-12-16 15:41:01.672678+00",
    song_title: "Tu sei santo",
    lyrics:
      "[G]Tutto è stato preparato qui\n[C]La casa e anche il mio cuore\n[Em]Tu sei il motivo per il quale [C]sono qui\n[G]I tuoi figli sono arrivati ormai\n[C]E ora siamo più di due o tre\n[Em]I cuori sono predisposti a bruciare per te\n[C]Tutti i versi e le canzoni che[Em] io canterò[C]\n[Em]Tutte le volte che mi prostro io v[C]oglio dirti che\n[Em]Tuo è il regno la gloria per sempre[D][C]\n[Em]Tuo è il dominio la forza amen amen[D][C]\n\nTu sei Santo\n[C]Tu sei Santo\n[Em]Nessun altro è come te\n[C]Nessun'altro è come te\n[Em]Nessun altro è come te\n[C]Nessun altro è come Gesù\n[C]Una cosa c[B]ercherò\n[Em]Quella di stare in tua presenza\n[D]Tutti i giorni della mia vita\n",
    author: "MORADA",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "6aecc366-827a-4c80-a5a1-950f889c5caf",
    created_at: "2024-12-15 22:11:47.855655+00",
    song_title: "Grande Signor",
    lyrics:
      "{comment: VERSO}\n[C]Sei amor, vita dai[Em]\n[D]Porti luce nel buio\n[C]Sei fedele, fai sperar[Em]\n[D]ogni cuore infranto\n[C]Grande Signor[D]\n[C]\n\n{comment: Coro}\n[C]e col cuor ti lodiamo[Em]\n[D]col respiro che tu hai messo in noi\n[C]e col cuor ti lodiamo[Em]\n[D]col respiro che tu ci hai dato\n[C]Grande signor[D]\n\n{comment: Bridge}\n[G]Di gioia grida il mondo inter\n[Am]e insieme ad esso noi cantiamo\n[C]Grande Signor",
    author: "All sons and daughters ",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "70236841-eedc-47d5-9023-3128752541ca",
    created_at: "2024-12-16 12:04:02.105971+00",
    song_title: "Quello che Dio dice di me - Chi Lui libera",
    lyrics:
      "[Intro]\n[G][G][C]\n\n{comment: Verse 1}\n[G]Chi son'io perché il grande Dio  Mi accolga a Sè[Em][D][G]\n[G]Ero perso e mi salvò  È il Suo amore[Em][D][C]\nÈ il Suo am[Em]ore[D][C]\n\n\n{comment: Chorus 1}\nChi Lui libe[G]ra Libero sarà[D]\nSono figl[Em]io [D]Su[C]o Si, è co[G]sì\n\n\n{comment: Verse 2}\n[G]Libertà Ora ho perché Mi riscattò[Em][D][G]\n[G]Vivevo in schiavitù  Ma Gesù morì[Em][D][C]\nSi, per me mor[Em]ì[D][C]\n\n{comment: Chorus 2}\nChi Lui liber[G]a Libero sarà[D]\nSono figli[Em]o S[D]uo[C] Si, è co[G]sì\nNella casa[G] Sua  Per me posto c'[D]è\nSono figli[Em]o S[D]uo[C] Si, è così[G]\n\n\n{comment:\"Bridge\"}\nSono scelto[Em] Credo a quello[D/F#]\nChe Dio di[G]ce di me[C]\nMi sostie[Em]ne Credo a quello[D/F#]\nChe Dio [G]dice di me[C]\n\n\n{comment: Tag}\nChe [Em]Dio dic[D/F#]e di me[C]",
    author: "Hillsong",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "71673aa0-2b40-4c6a-9bcd-9f7f879c275c",
    created_at: "2024-12-11 20:53:58.629646+00",
    song_title: "A colui che siede sul suo trono",
    lyrics:
      "{comment: Verse 1:}\n[G]Voglio conoscerti\nsape[Em]re di te ogni giorno di più\n[Am]e stare alla tua presenza e adorar[C]ti\n[G]Rivela la tua gloria\n[Em]vogliamo molto di più di te\n[Am]vogliamo la tua presenza Ges[D]ù\n\n{comment: Chorus:}\n[G]A colui che siede sul suo trono\n[Em]E che vive per sempre in eterno\nSia la gloria[Am], sia l’ono[D]re e il poter\nSia la gloria[Am], sia l’ono[D]re e il poter\n\n{comment: Instrumental:}\n[C] [Em] [G] [C] [Em] [Bm] [C]\n\n{comment: BRIDGE:}\n[C]Santo santo tu sei [G]santo\n[C]Santo è il Signor[D]",
    author: "Lucas Conslie and Toma Tu Lugar",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "71ca00aa-6ce0-4556-abf7-2dd96af3591a",
    created_at: "2024-12-16 12:17:47.321111+00",
    song_title: "Rompo il mio vaso",
    lyrics:
      '{comment: "Verso"}\n[B]Ai tuoi piedi sto[B/D#]\nArrendo tutto ciò che sono a te tut[E]to ciò che ho\n[B]Ricevi qui Signore il mi[B/D#]o profumo\ne le la[E]crime che verserò[F#]\n\n\n{comment:"Precoro"}\n[C#m]Basta uno sguardo al tuo volto[B/D#]\nMi hai perd[G#m]onato fin dal primo giorno[E]\n[C#m]E tutti i miei[B/D#] tesori i[G#m]o verserò davanti a te[F#]\n\n\n{comment:"Coro"}\nIo ro[B]mpo il mio vaso io rompo il mi[B/D#]o vaso\nAi tuoi pie[E]di ai piedi del mio amato\nIo ro[B]mpo il mio vaso io rompo il mi[B/D#]o vaso\nAi tuoi pie[E]di ai piedi del mio [G#m]amato[F#]\n\n\n{comment:"Bridge"}\nE non importa il prezzo[B]\nDel profumo che ho versato[B/D#]\nLa tua presenza vale di più[E]\nLa tua presenza vale di più\n\n',
    author: "Luma Elpidio",
    upload_key: "B",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "744f546d-1f58-42a7-ab85-bc30ec1db016",
    created_at: "2024-12-11 21:20:32.258615+00",
    song_title: "Canterò per Te",
    lyrics:
      "{comment: Intro:}\n[F#m][E][D][E]\n\n{comment: Verse 1:}\n[A]La voce e le mani al[D]zo a te\nElevo a [A]te la mia l[D]ode\n[E]Amo [F#m]te piu’ di qu[E]anto possa d[D]ire\n[E]Amo [F#m]te piu’ di qu[E]anto possa d[D]ire\n\n{comment: Chorus:}\nCanter[A]ò per [A/C#]te, solo [D]te ador[E]ero\nPer la gl[A]oria [Bm]tua, solo t[D]e io ser[E]virò\nAnche [F#m]se il mo[E/G#]ndo cadr[D]à[E]\nIl mio c[F#m]anto a[E/G#] te andr[D]à\nSolo [E]te adorero[A][A/C#][D][E]\n\n{comment: Bridge:}\nTi am[A]erò [A/C#] per sempre o Di[D]o[E]",
    author: NaN,
    upload_key: "A",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "765362b6-7a76-4dda-8f7e-11e923dc59c5",
    created_at: "2024-12-15 22:15:31.770889+00",
    song_title: "Puoi incontrarmi ora qui - Here again",
    lyrics:
      "[{comment: Verso 1}]\n[A]Non [Bm]si può [G]tornare indietro\n[A]Ne s[Bm]aper qu[G]el che succederà\n[A]Ma i[Bm]o so ch[G]e qui nel mezzo\n[A]È do[D/F#]ve la tua[G] promessa avverrà \n\n[{comment: Coro}]\n[D]Senza di[A] Te non sono niente\n[Bm]Puoi in[G]contrarmi ora qui?\n[D]Quel che v[A]orrei è ciò che Tu sei\n[Bm]Puoi incontra[G]rmi ora qui?\n\n[{comment: Verso 2}]\nSe cammino nella valle\nLe Paure il tuo amor coprirà \nCome il sole che risplende\nLa tua gloria risplenda in me\n\n[{comment: Bridge}]\nNon mi hai lasciato[D]\nNeanche un minuto[A/C#]\nLa tua presenza è qui[Bm]\nLa tua [A]presenza è qui[G]\nSpirito santo [D]\ndai[A/C#] vita ai morti\nLa t[Bm]ua presenza è qui\nL[A]a tu[G]a presenza è qui \n\n\n\n",
    author: "Elevation Worship",
    upload_key: "D",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "76841bd2-6b31-4587-9e68-4e3ad76c051b",
    created_at: "2024-12-16 14:41:41.268091+00",
    song_title: "Tra le tue braccia",
    lyrics:
      '{comment: "VERSO"}\n[A]Sicuro tra le braccia\nDi colui che mai mi abbandonò[E]\n[A]Il tuo amore perfetto è sempre stato\nVivo dentro di me[E]\n\n{comment:"PRECORO"}\nSe passerò per[C#m] la valle\nTroverò conforto nel [A]tuo amore[B]\nPerché so che tu sei i[F#m]l mio rifugio sic[C#m]uro[A][B]\n               \n{comment:"CORO"}\nTra le tue braccia trovo r[A]iposo\nTra le tue braccia trovo [E]riposo\nTra le tue braccia trovo[A] riposo\nTra le tue braccia trovo [E]riposo\n\n{comment:"BRIDGE"}\n[A]Ritorno alla grazia\n[E]Mi arrendo di nuovo a Te',
    author: " Laura Souguellis",
    upload_key: "A",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "775b16e2-b904-461a-9245-15e88968d4ff",
    created_at: "2024-12-16 09:39:34.682647+00",
    song_title: "Il tuo amor non fallirà",
    lyrics:
      '\n{comment:"VERSO 1:"}\n[G]Più grande di ogni mia diffi[D]coltà[A]\nPiù pot[G]ente della [D]morte sei Ge[A]sù\n[G]Fedele nelle [D]mie avversit[A]à\nIl Tuo a[G]mor[D] rimarr[A]à\n\n{comment:"CORO:"}\n[Bm]Il Tuo amor non fallirà\nMai m[G]eno verrà\n[D]Mai mi lasce[A]rà\n\n{comment:"VERSO 2:"}\nPiù in a[G]lto di ogni al[D]tra cosa va[A]\nSoddisfa [G]e travolge [D]la mia anima[A]\nE n[G]on avrò pau[D]ra perché [A]so che\nIl Tuo [G]amor[D] rima[A]rrà\n\n{comment:"BRIDGE:"}\nNella gio[G]ia, nel do[D]lor, ho fe[A]de\nChe so[Em]no coperto d[G]al Tuo gr[D]ande amo[A]re\nIl mio [G]debi[D]to Tu h[A]ai pagato e nie[Em]nte\nMi sep[G]arerà[D] da [A]Te',
    author: "Jesus Culture",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "84227837-7ffe-4bfb-968c-f15d8f544790",
    created_at: "2025-04-23 14:32:04.556236+00",
    song_title: "Firm foundation",
    lyrics:
      "Cristo è il mio fondamento, la [G]roccia su cui sto[Em][D]\nQuando tutto intorno è scosso, s[G]icuro io starò[Em][D]\nPerché la mia fede è in Gesù, [C]Lui non de[G/B]lude mai[Em][D]\nFedele in ogni tem[C]po, potrà [G/B]fallire mai?[Em][D]\nLui no, [G]lui no[G]\n\nAnche nella tempesta, la Sua pa[G]ce sentirò[Em][D]\nSolo in Lui trovo forza, non aff[G]onderò, perché[Em][D]\nCristo è il mio fondamento, Lu[C]i non delu[G/B]de mai[Em][D]\nFedele in ogni tem[C]po, potrà [G/B]fallire mai?[Em][D]\nLui no, [G]lui no[G]\nLui non ha fall[Em]ito ma[D]i, Lu[C]i non ha fallito ma[Em]i,[D][C]\n\n[|][Cma7][/][D][/][|][G/B][/][Em][D][|]\n\n[C]Pioggia e vento sof[D]fiano contro m[G/B]e[Em][D]\n[C]Ma la mia casa è fo[D]ndata su di[G/B] Te[Em][D]\n\n[C]Mai smosso io sarò,[D] perché sul[G/B]la roccia sto[Em][D]\n[C]con te ce la farò p[D]erché sulla[G/B] roccia sto[Em][D]",
    author: "Cody Carnes",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: NaN,
  },
  {
    id: "8446322d-327a-43a6-af86-36c2afbfc810",
    created_at: "2024-12-15 22:17:12.735058+00",
    song_title: "Home ",
    lyrics:
      "{comment: Verse 1}\n[Bb]Dal f[Cm7]reddo dal b[F/A]uio Dal mio[Bb] vagare\n[Bb/D]Tu Mi hai ac[Eb]colto e ch[F]iamato per[Bb] nome\n[Bb]Il tu[Cm7]o calore Ha[F/A] scaldato i[Bb]l mio cuore \n[Eb]Nella tua casa Per sempre[F] starò;[Bb]\n\n\nPre-{comment: Coro}\n[Gm]Oh o[F]h s[Bb/D]ono q[Eb]ui’ \n[Gm]Oh o[F]h i[Bb/D]o cant[Eb]ero[Eb]\n\n{comment: Chorus}\n[Eb]Per sempre tu sei mio Padr[F]e e Re[Gm]\n[Bb]Per sempre tu regni su di me[Dm][Eb]\n[Eb]tra le tue bracc[F]ia aperte so[Gm][F][Eb]\n[Gm]Da solo non sarò U[F]na casa ora ho[Bb]\n\n{comment: Instrumental}\n[Bb][/][/][Bb][/][/][Bb][/][/][Bb]\n[Gm][F][Bb][Eb]\n[Gm][F][Bb][Eb]\n\n\n{comment: Verse 2}\n[Bb]Mi ha[Cm7]i dato un p[F/A]osto vicino[Bb] a te\n[Bb/D]Alla tua tav[Eb]ola Sazio [F]sarò’[Bb]\n[Bb]Sin d[Cm7]al principi[F/A]o Alla fine[Bb] staro’\nAll[Eb]a tua presenza mi arrende[F]rò[Bb]\n\n{comment: Bridge}\n[Eb]Io so [F]che t[Gm]u hai p[Bb]reparato Un posto migliore per[Eb] me [F][Bb/D]\n[Eb]appart[F]engo [Gm]a una n[Bb]uova famiglia È la tua chiesa [Eb]Gesù[F][Bb/D]",
    author: "C3LA",
    upload_key: "Bb",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "88ca2545-f9be-4211-93b1-7cf60222d4b8",
    created_at: "2024-12-16 09:49:03.551673+00",
    song_title: "La croce ha l'ultima parola",
    lyrics:
      '\n{comment:"VERSO 1:"}\nLa [G]croce ha l’ulti[C/G]ma P[G]arola\nLa croce ha l’ulti[C/G]ma p[G]arola\nE se il dolo[Em]re verrà a porta[C]re il buio\nLa [D]croce ha l’ultima paro[G]la\n\n{comment:"VERSO 2:"}\nLa [G]croce ha l’ulti[C/G]ma p[G]arola\nLa croce ha l’ulti[C/G]ma p[G]arola\nIl ma[Em]le potrà innalzarsi [C]contro di me\nMa la [D]croce ha l’ultima paro[G]la\n\n{comment:"VERSO 3:"}\nLa [G]croce ha l’ulti[C/G]ma p[G]arola\nLa croce ha l’ulti[C/G]ma parola[G]\nil redento[Em]re verrà come[C] luce al mattino\nLa [D]croce ha l’ultima paro[G]la\n\n{comment:"VERSO 4:"}\nLa [G]croce ha l’ulti[C/G]ma p[G]arola\nLa croce ha l’ulti[C/G]ma p[G]arola\nHa scambiato[Em] la morte per la[C] vita eterna\nLa [D]croce ha l’ultima paro[G]la\n\n{comment:"CORO:"}\nNiente è più [Em]forte né più [C]alto\nNé più[G] grande del tuo nome [D]Gesù\nTutto l’ono[Em]re e la poten[C]za\ntutta la [G]gloria al tuo nome [D]Gesù',
    author: "Cody Carnes",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "8941bcf6-eefa-4a02-bf12-42dd386b53fe",
    created_at: "2024-12-16 15:43:07.141428+00",
    song_title: "Un altro in mezzo al fuoco",
    lyrics:
      "{comment: \"Verso 1:\"}\n[Bm]Sei la via quando il [G]cuore è nella [D]prova,\n[Bm]la grazia che ogni [G]muro abbatterà[D]\n[Bm]Anche se so che [G]è difficile non arrender[D]si e combattere[A/D],\n[Bm]lo so che non [G]sarò solo [D]mai\n\n{comment: Chorus}\nC'era un altro in mezzo al [Bm]fuoco [G]Li affianco a [D]me\nC'era un altro nelle [Bm]acque Che mise il [G]mare a tacer[D]\nE se mi dimentica[Bm]ssi Come hai [G]liberato [D]me\nLa sua croce mostra il [Bm]prezzo Che Gesù[G] pagò per m[D]e\nC'era un altro in mezzo al fuo[Bm]co  [G]  [D]\n\n{comment: Verse 2}\nIl mio passato hai gettato in fondo al mare\nNon sono più schiavo del peccato, no\nE se un giorno io cadrò mi rialzerò e camminerò\nGuardando avanti io mai mi volterò\nPerché so che solo mai sarò\n\n{comment:\"Bridge\"}\nNel buio vedo una lu[Bm]ce Che [G]splende\nE il male [D]che si arrende a [A]te\nDal cielo ruggi[Bm]rai\nOgni [G]muro tu abbatte[D/F#]rai per [G]me\nLa terra tre[Bm]ma ed ogni cate[G]na\nDavanti a [D/F#]te si spezze[A]rà\nNiente ci sepa[Em]ra\nniente ci sepa[G]ra  [A]\n\n{comment: Verse 3}\nNon c'è niente e nessuno come Gesù\ncolui che e era che è e che sarà\nanche se non so cos avverà, la tua verità, no non fallirà\nlo so che non sarò solo mai\n\n",
    author: "Hillsong",
    upload_key: "D",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "8bc6a820-7a37-4e52-ab4c-efcedec5461a",
    created_at: "2024-12-11 21:29:25.116369+00",
    song_title: "L’acqua in vino cambiò",
    lyrics:
      "{comment: Verse 1:}\n[Em]L’acqua in [C]vino ca[G]mbiò\n[Em]Vista al ci[C]eco don[G]ò\nNon c’è nessu[Am]no\nCome T[D]e\n\n{comment: Verse 2:}\n[Em]Luce nel buio[C] Tu se[G]i\n[Em]Colui che vit[C]a ci d[G]à\nNon c’è nessu[Am]no\nCome T[D]e\n\n{comment: Chorus:}\n[Em]Dio è più grande, Dio è più for[C]te\n[G]è al disopra di ogni altro[D]\n[Em]Tu che guarisci, sei gran[C]de in forza\n[G]Signor, signor[D]\n\n{comment: Bridge:}\n[Em]Se Dio è per noi, chi ci po[C]trà fermare\n[G]Se Dio è con noi, chi mai ci ferme[D]rà\n",
    author: "Chris Tomlin",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "8bd11351-737c-4daf-87e4-181ea3956f8c",
    created_at: "2024-12-15 22:14:01.980193+00",
    song_title: "Guardo al calvario",
    lyrics:
      "\n{comment: Verso 1}:\nGuardo il calv[Eb]ario e il sacrificio\nDove G[Bb]esù mori per[Cm] me\nIl sangue s[Ab]uo versato[Eb/G] fu\nCon grande a[Bb]mor soffri per [Eb]me[Gm][Ab]\n\n{comment: Verso 2}:\nOgni peccato e[Eb]d oppressione\nSulla [Bb]croce lui po[Cm]rtò\nIl corpo su[Ab]o trafitto[Eb/G] fu\nIl Salva[Bb]tor, il Re dei [Eb]re[Gm][Ab]\n\n{comment: Coro}:\n[Eb]Noi ti lodiamo oh Si[Ab]gnore e r[Eb]e\nGlo[Cm]rifichiam il no[Bb]me tuo\nPer [Eb/G]sempre noi cant[Ab]eremo a[Cm] te\nS[Ab]ignor sei il no[Bb]stro D[Eb]io[Gm][Ab]\n\n{comment: VERSO 3:}\nIl terzo gi[Eb]orno glorioso fu\nGesù i[Bb]l Messia ris[Cm]uscitò\nIl Dio del [Ab]ciel,viven[Eb/G]te è\nLa morte n[Bb]on ha più po[Eb]ter[Gm][Ab]\n\n{comment: VERSO 4:}\nLui torne[Eb]rà in bianche vesti\nLa glo[Bb]ria sua risp[Cm]lenderà\nCi porterà [Ab]lassù con [Eb/G]se\nE il volto s[Bb]uo noi guard[Eb]erem[Gm][Ab]",
    author: "Hillsong",
    upload_key: "Eb",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "8f167452-53f6-41c1-aa18-1861ecf35ba9",
    created_at: "2024-12-11 21:28:05.859312+00",
    song_title: "Dio dei miracoli",
    lyrics:
      "\n{comment: INTRO:}\n[F#m7][C#m][D2][D2]\n\n{comment: Verse 1:}\n[F#m]Colui che ha dato la[C#m] vista ai ciechi\nSi st[D]a muovendo proprio qui\nMuovendo qui davanti a me\n[F#m]Colui che ha fatto s[C#m]entire i sordi\nSta can[D]cellando le paure\nLe paure dentro me\n\n{comment: Chorus:}\n[F#m]Io credo in te\n[D]Io credo in te\n[A]Dio dei miraco[E]li\n\n{comment: Verse 2:}\n[F#m]Colui che fa l impos[C#m]sibile\nSta ope[D]rando nel mio cuore\nSta operando nel mio cuore\n[F#m]Colui che ha distrut[C#m]to la morte\nHa mes[D]so la sua vita in me\nHa messo la sua vita in me\n\n{comment: BRIDGE:}\n[D]Il Dio che era e [E]che verrà\nLa pot[A/C#]enza del [F#m]risorto re\nIl D[D]io che da la v[E]ita ai morti\nIl Dio dei mi[A]racoli",
    author: "Jesus Culture",
    upload_key: "A",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "944698c1-a855-4089-a4d6-37f232e81ad9",
    created_at: "2024-12-16 09:40:14.051883+00",
    song_title: "Innalzo un Alleluia",
    lyrics:
      '{comment: "Verso"}\nInnalz[G]o un alleluia davanti ai miei n[C]emici\nInnalz[Em]o un alleluia sopra all\'in[D]credulità\nInnalzo[G] un alleluia mi armo di una mel[C]odia\nInnalzo[Em] un alleluia il cielo lott[D]a già per me\n\n{comment:"Coro"}\n[C]Io Canterò in mezzo al[G]la tempesta\n[Em]Sempre più forte la mia lo[D]de ruggirà\n[C]Una volta ancora la sp[G]eranza sorgerà\nL[Em]a morte è sconfitta il Re [D]è vivo\n\n{comment:"verso"}\nInnalzo un alleluia con tutto quello che è in me\nInnalzo un alleluia il male fuggirà da me\nInnalzo un alleluia davanti ai misteri\nInnalzo un alleluia la paura non ha forza in me\n\n{comment:"bridge"}\n[G]Cantalo più forte! (Davanti ai miei nemici)\n[C]Cantalo più forte! (Sopra l\'incredulità)\n[Em]Cantalo più forte! (Mi armo di una melodia)\n[D]Cantalo più forte! (Il Cielo lotta già per me)',
    author: "Bethel",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "973fe445-6a09-4225-9302-b9f642b364c2",
    created_at: "2024-12-16 09:40:56.257478+00",
    song_title: "Io mi arrendo",
    lyrics:
      '\n{comment:"VERSO 1:"}\n[C#m]Sono qui sulle gin[E]occhia, qui\nAspette[B]rò, aspette[A]rò\nSt[C#m]ringimi tra le Tue bra[E]ccia qui\nIo cerco [B]Te, io cerco [A]Te\nIo mi arr[C#m]endo....[B][F#m][A]\n\n{comment:"VERSO 2:"}\n[C#m]Riempimi fino in prof[E]ondità\nHo fame di T[B]e, ho fame di [A]Te\n[C#m]Io so che senti il mio gr[E]ido a Te\nParlami ade[B]sso, parlami ades[A]so\n\n{comment:"CORO:"}\nIo mi[C#m] arrendo, io mi arr[E]endo\nVoglio c[F#m]onoscerti, voglio conoscer[A]ti[B]\n\n{comment:"BRIDGE:"}\nCome un ve[A]nto c[E]he soffia den[B]tro me\nFa ciò che [F#m]vuoi, fa ciò che [C#m]vuoi in [B]me',
    author: "Hillsong",
    upload_key: "E",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "9aad5647-7235-420b-a1a0-25826ffef871",
    created_at: "2024-12-16 10:22:51.953788+00",
    song_title: "Nessuno è come te",
    lyrics:
      '{comment: "Coro:"}\n [G]Nessuno è com[D]e Te[C][G][C]\nNessun altro[G] sa capire il mio[Am] cuor[D]\n[G]Se cercassi[D] per l’eternità[C]\nNon troverei n[G]essuno come Te[D][G]\n\n{comment:"VERSO:"}\n[C]La Tua bontà scorre come un fium[G]e[Em]\n[C]sempre guarisce i[D]l mio cuor[G]\n[C]fra le Tue braccia mi sento al s[G]icuro[Em][Am]\nnessuno è come T[C]e[Dsus][D]',
    author: "Unknown",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "9d5147c3-fbaa-4d88-922b-c5ebd0ff34e0",
    created_at: "2024-12-11 21:31:19.341932+00",
    song_title: "Dio grande Dio",
    lyrics:
      "\n{comment: Verse 1:}\n[G]Glorioso Re dei Re,\n[Em]Vestito di Maestà\nLa terra gi[C]oirà, la terra gioirà[D]\n[G]C'è luce intorno al Re\n[Em]La voce sua si udrà\nIl male tremerà[C], il male treme[D]rà\n\n{comment: Chorus:}\n[G]Dio grande Dio\nCanta che Dio è gra[Em]nde Dio\nE si vedrà che gra[C]nde Dio[D]\nE‘ il nostro D[G]io\n\n{comment: Verse 2:}\n[G]Il tempo è in mano a Te , E[Em]terno senza età\nPrincipio e fine sei, Pr[C]incipio e fine s[D]ei.\n[G]Padre Figlio e Spirito, So[Em]vrana trinità\nIl leone e l' Agnel, I[C]l Leone e l'Agn[D]el\n\n{comment: Bridge:}\n[G]Tutto sei per me\n[Em]Tu sei degno di lode\n[C]Ilmio cuore can[D]ta che\nSei [G]grande",
    author: "Chris Tomlin",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "a08cf887-fb5c-4be2-a5d7-935992c63b93",
    created_at: "2024-12-16 12:18:26.253805+00",
    song_title: "Praise - Loda",
    lyrics:
      '{comment: "VERSO 2"}\n[G]Ti lodo sul monte e nella vall[C]e[G]\n[D]Ti lodo nel dubbio e nella ce[C]rtezza[G]\n[G]Quando sarò solo o se circonda[C]to[G]\n[D]Perché la mia lode distrugge [C]i nemici[G]\n[D]Finché respiro ho un motiv[C]o per dire\n\n{comment:"CORO"}\n[Em]Looooooda[C] il Signore a[G]nima mia[D]\n[Em]Looooooda[C] il Signore a[G]nima mia[D]\n\n{comment:"VERSO 2"}\nQuando me la sento e quando non voglio\nTi lodo perché so che hai il controllo\nLa mia lode è un\'arma ed è più di un suono\nLa mia lode è il grido che abbatte le mura\n\n{comment:"CORO 2"}\n\n[Em]Looooooda[C] il Signore a[G]nima mia[D]\n[Em]Looooooda[C] il Signore a[G]nima mia[D]\nNon starò zitto il mio Dio è vivo\nCome potrei non gridare\nLooooooda il Signore anima mia\n\n{comment:"SPECIAL"}\n[G]Ti lodo perché tu regni e [C]sei il re\nSei re[D]suscitato e hai sconfitto la [C]morte\nTu sei fedele sei la verità\nNon c\'è nessuno più grande di te\n[G]Ti lodo perché tu regni e se[Am]i il re\n[Em]Sei resuscitato e hai sconfit[D]to la morte\n[G]Tu sei fedele sei la verità[Am]\n[Em]Non c\'è nessuno più grande di[D] te\n\n',
    author: "Elevation Worship",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "b29ccfdf-c423-411c-a431-b7727d3419d2",
    created_at: "2024-12-16 09:50:08.771442+00",
    song_title: "La Tua Presenza",
    lyrics:
      '{comment: "VERSO:"}\n[D]Sicuro Nelle Tue Mani\n[Em]Adesso Io Non Ho Paura C[G]\'è\nLa Tua Pres[D]enza\n[D]Quello Che Ho Non Vale Più\n[Em]Ciò Che Io So Perde Valore C[G]\'è\nLa Tua Presenza[D]\n\n{comment:"PRE-CORO:"}\n[Bm]Il Cielo T[A]rema Davanti Al Cre[G]ato\n[Bm]Regni E Naz[A]ioni Si Inchinano A [G]Te\n\n{comment:"CORO:"}\nLa Tua Pre[D]senza Scioglie Il Mio [A/C#]Cuore\nLa Tua Presenz[Bm]a Unisce Il Ci[A]elo e La T[G]erra\nLa Tua Pre[D]senza Io Sento Qui[A/C#]\nLa Tua Presenz[Bm]a È Ciò Che Va[A]le Di Più[G]\n\n{comment:"BRIDGE:"}\n[Bm]Santo, G[A]iusto, G[G]rande Me[D/F#]raviglioso Sei',
    author: "New Life Worship",
    upload_key: "D",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "b4120a4a-47d4-41f7-9b72-59e0ce80dfe1",
    created_at: "2025-04-15 13:23:02.457639+00",
    song_title: "Oh lord you're beautiful",
    lyrics:
      "Verse 1\nOh [ C]Lord You’re [ F][ C/E][ G]beautiful\nYour [ C]face is [ F]all [ C/E]I [ G]see\nAnd [ A m]when Your [ E]eyes are [ F]on [ G]this [ C]child\nYour [ D m7]grace [ G]abounds to [ C]me\n\nVerse 2\nOh [ C]Lord please [ F]light [ C/E]the [ G]fire\nThat [ C]once burned [ F]bright [ C/E]and [ G]clear\n[ A m]Replace the [ E]lamp of [ F]my [chord G]first [ C]love\nThat [ D m7]burns with [ G]Holy [ C]fear\n\nChorus\nI want to [ F]take [ C/E]Your [ D m7]word [ C]and [ G]shine it all [ C]around\nBut first help me [ F]just to [ A m]live it [ G]Lord\nAnd when I’m [ F]doing [ C/E]well [ D m7]help [ C]me\nTo [ G]never seek a [ C]crown\nFor my [ F]reward is [ C/E]giving [ D m]glory [ G]to [ C]You",
    author: "Keith Green",
    upload_key: "C",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: NaN,
  },
  {
    id: "be6025b7-3098-4bed-85a9-855352ca0f16",
    created_at: "2024-12-16 10:24:59.237722+00",
    song_title: "Non c'è posto migliore",
    lyrics:
      "[G]Non c'è posto migliore\n[C]Non c'è posto migliore\n[Em]Non c'è posto migliore\n[C]Che qui nel tuo amor, qui nel tuo amor\n\n[G]Accendi un fuoco dentro al mio cuore\n[C]Fa' che nessuno possa spegnerlo\n[Em]Voglio più di Te Signor, \n[C]voglio più di te Signor",
    author: "Unknown",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "c11d7d48-a4d3-4aa2-a3d7-9de8a0b3677e",
    created_at: "2024-12-16 12:17:08.620245+00",
    song_title: "Ritorno a te",
    lyrics:
      '{comment: "VERSO:"}\n[E]Quando vengo a Te solo e semp[B]lice[A]\nSiamo solo n[B]oi\n[E]Spero proprio che ciò che h[B]o per Te[A]\nTi raggiunga il cuo[B]r\n\nPRE-CORO:\n[F#m]Il canto che of[E]fro a Te[B]\nDice tutto di me\n[F#m]Spero che lo am[E]erai[B]\n[F#m]Tu chiedi since[E]rità cerchi profond[B]ità\n[F#m]Tu guardi dentr[E]o al mio cuor[B]\n\n{comment:"CORO:"}\n[A]Torno alla vera adorazione[B]\nE ri[F#m]torno a Te sol[A]tanto a Te Gesù[B][E]\nM[E]i pento per quello che ne ho fatto[B]\nQuando[F#m] guardo a Te  Soltanto[A] a Te Ge[B]sù[E]\n\n{comment:"VERSO 2:"}\nChi può esprimere il dolore Tuo\nMio eterno Re\nEd io sono qui solo e semplice\nAppartengo a Te',
    author: "Matt Redman",
    upload_key: "E",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "c6faf7a3-b7a3-4a8e-8f82-1f0bb09bc2bd",
    created_at: "2024-12-16 12:31:06.686669+00",
    song_title: "Santo Spirito",
    lyrics:
      '\n{comment:"CORO:"}\n[A]Santo Spirito si scendi qui\n[D]Riempi questa chiesa e cambiami[Bm]\n[A]Io voglio dare la mia lode a Te\n[D]Con la tua presenza riempimi di Te[Bm]\n\n{comment:"VERSO 1:"}\n[A]Non c’è nulla che\nSia pari a Te[D] Non c’è nulla che\nSperanza mi dà   Ma[A] Tu Gesù[D]\n[A]Io solo con Te\nSent[D]o l’amore che    Porta la libertà\nE gioi[A]a mi dà\nSe[D]i Tu Gesù\n\n{comment:"BRIDGE:"}\n[Bm]Fammi ca[A/C#]pire l’[D]importanza della[E] croce\n[Bm]Voglio s[A/C#]entire d[D]entro me la Tua [E]presenza[D]',
    author: "Bethel",
    upload_key: "A",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "cab26ba3-9e34-41c3-a2ed-7468ec8fc84f",
    created_at: "2024-12-16 14:42:19.882512+00",
    song_title: "La tua fedeltà - Tu fidelidad",
    lyrics:
      '\n{comment:"Verso 1:"}\n[C]la tua fedelta e’ g[F]rande\n[G]la tua fedelta e’ incom[C]parabile\n[Am]nessuno e’ come te\nPadre  d[F]\'amor\ng[G]rande e’ la tua fedelta[C]\n',
    author: "Unknown",
    upload_key: "C",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "d76a7e02-abae-41e1-95a6-924c051baeeb",
    created_at: "2024-12-15 22:26:58.440711+00",
    song_title: "Il mio Dio è amore",
    lyrics:
      '{comment: "VERSO:"}\n[E]Ogni cuore ogni anima[B]\nogni nazione ogni lin[C#m]gua\nTrove[B]ranno in te la speranz[A]a\n[E]il creato si inchiner[B]à\nocchi al cielo e Ti ved[C#m]rà\nSalvat[B]ore per sempre in eter[A]no\n\nPRE-CORO:\nQuesto è a[E]mor[B]\nSulla croce[C#m]\nHai dato la tua vita a n[A]oi[E][B]\nLe nostre v[C#m]oci alziamo \n[A]E cantiamo a Lu[C#m]i\nNon c\'è pi[B]ù paura in [A]me\n\n{comment:"CORO:"}\nIl mio Dio è a[C#m]more[A][B]\nIl mio Dio è amore\n\n{comment:"VERSO:"}\nOgni cuore che piangerà\nogni braccio alzato a Te\ntroveranno in Te la speranza\ne per sempre Ti adorerem\nsia tutta la gloria a Te\nSalvatore per sempre in eterno!\n\n{comment:"BRIDGE:"}\n[A]Per sempre [E]canterò[B]\ntutto [C#m]quel che hai fatto in [A]me\ntutta la t[E]erra cant[B]erà\nle tue mer[C#m]aviglie e..',
    author: "Unknown",
    upload_key: "E",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "d97adb60-6c2a-4aa3-bbaf-cf36204daa0e",
    created_at: "2024-12-16 12:00:47.825979+00",
    song_title: "Per sempre",
    lyrics:
      '{comment: "INTRO:"}\n[A][E][Bm][D]\n\n<—- accordi di tutta la canzone\n[A][E][F#m][D]\n\n{comment:"VERSO:"}\nLe stelle ed il sole\nsi spensero al dolor\nMorì il Salvator del mondo\nIl corpo sulla croce\nE il Sangue Suo versò\nDi ogni male prese il peso\n\n{comment:"INTRO:"}\n\n{comment:"VERSO 2:"}\n\nUn ultimo  respiro\nGuardando la creazione\nE Gesù scese nell’oscurità\nUna guerra iniziò\nL’inferno vinto fu\nLa morte non ha più potere\n\n{comment:"PRE-CORO:"}\n\nLa terra che tremò\nLa pietra rotolò\nIl Suo perfetto amore mi salvò\nDov’è il Tuo dardo, oh morte?\nIl Re risuscitò\nNoi siamo vincitori\n\n{comment:"CORO:"}\n\nPer sempre Lo glorifichiam\nPer sempre noi lo innalziamo\nRisuscitò è Gesu’\nvive ancora, vive ancora\n\n{comment:"BRIDGE:"}\n\nCantiamo Alleluia\nCantiamo Alleluia\nCantiamo Alleluia\nL’agnello è il Vincitor',
    author: "Kary Jobe",
    upload_key: "A",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "dade10e7-3e97-4294-accb-48a3c0686286",
    created_at: "2024-12-16 14:48:11.575934+00",
    song_title: "Tu sei buono Signor (Oh Signore vengo a Te) ",
    lyrics:
      '{comment: "VERSO 1:"}\nTu sei buo[G]no Signor, quando in me non c’è bontà\nTu sei amo[D]re Signor, tutto il mondo lo vedrà\nSei la luce Si[G]gnor, anche nell’oscurità\nLa speranza Tu [D]sei, il perdono ho avuto in Te[G]\n\n{comment:"VERSO 2:"}\n\nSei la pace Signor, quando la paura c’è\nSei la mia verita, quando il dubbio è dentro me\nSei la gioia Signor, canterò soltanto a Te\nSei la vita Gesu, in Te morte non c’è più\n\n{comment:"CORO:"}\n                \n[G]Oh Signore vengo a [D]Te\nSignore vengo a [Em]Te\nE nelle braccia Tue ripo[D]so trove[C]rò\nNon c’è nessu[Em]no [D]come [C]Te\nLuce del mon[Em]do [D]regne[C]ra[G]i\n\n{comment:"VERSO 3:"}\n\nSei di più, sei di più, chi potrà descrivere\nTu sei il Re, sei il Signor, il creato adore Te\nTu sei qui, Tu sei qui, il Tuo volto cercherò\nTu sei Dio, Tu sei Dio, la mia vita ti darò\n\n{comment:"BRIDGE:"}\n                                  \n[Em]Io canterò [C]soltanto a Te\n[G]Gesù [D]Gesù[C]\n',
    author: "Unknown",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "db5f28aa-a4cb-4453-a6e3-6d1a28fc3ec7",
    created_at: "2024-12-16 12:30:36.882211+00",
    song_title: "Santo per sempre",
    lyrics:
      '{comment: "Verso"}\n[G]Mille generazioni ad[C]orano in ginocchio[G]\n[Em]Cantano al Signore un[D] canto eterno[C]\n[G]E chi ci ha precedut[C]i e chiunque crederà[G]\n[Em]Canterà al Signore un[D] canto eterno[C]\n\n{comment:"Precoro"}\n[C]Il tuo nome [Em]è il più alto il tuo [D]nome è il più grande\nIl tuo[Em] nome è sopra ogni altro nome[C]\n[C]Sui troni e [Em]i domini [D]potenze e regni\nIl tuo n[Em]ome è sopra ogni altro nome[Am]\n\n{comment:"Coro"}\nEd il cielo [C]grida [Em]santo[D] il creato gri[G/B]da santo[Em]\nInnalziamo Te[Am] santo[D] Santo per sempre[G]\n\n{comment:"Verso 2"}\nS[G]e Dio ti ha perdonato sei[C] stato riscattato[G]\n[Em]Canta all\'agnello un [D]canto eterno[C]\n[G]Se vivi in libertà e[C] porti il suo nome[G]\n[Em]Canta all\'agnello un [D]canto eterno[C]\n[Em]Canteremo per s[D]empre e amen[C]\n\n{comment:"Coro"}\nEd il cielo [C]grida [Em]santo[D] il creato gri[G/B]da santo[Em]\nInnalziamo Te[Am] santo[D] Santo per sempre[G]\nLa tua chiesa[C] canta[Em] san[D]to al re [G/B]dei re santo[Em]\nTu sarai per sem[Am]pre santo[D] santo per sempre[G]',
    author: "Bethel",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "e07226ac-d78f-4180-b56a-f05a3f7f1a46",
    created_at: "2024-12-16 12:33:45.209861+00",
    song_title: "Sono forte se spero",
    lyrics:
      '{comment: "VERSO:"}\n[B]Sono forte\n“Se spero nel [F#]Signore” x3\n\n{comment:"PRECORO:"}\n[B]Oh D[E]io r[B]egn[E]i per[F#] sem[G#m]pre[F#]\n[B]Tu s[E]ei i[B]l m[E]io li[F#]ber[G#m]ator[F#]\n\n{comment:"CORO:"}\n[B]Eterno Dio etern[E]o amor\nEterno se[G#m]i Signor\nNon cambi[E] mai Tu [F#]sei da semp[E]re[F#]\n[B]Se cado m[E]i rialzerai\nTu mi ri[G#m]alzerai\nE in [E]alto volerò\n[F#]Lassù[E] con [F#]Te[E][B]',
    author: " Brenton Brown",
    upload_key: "B",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "e1a42f46-7763-43cc-8574-32a457d7a10d",
    created_at: "2024-12-16 10:26:48.633181+00",
    song_title: "Non mi lascerai",
    lyrics:
      '{comment: "VERSO:"}\n[A]Se camminerò nella notte, Tu cammini con me\nIl[D] Tuo amore mi salverà\n[A]Se mi perderò so che Tu, il mio aiuto sarai\nL[D]a Tua mano mi coprirà\n\n{comment:"PRE-CORO:"}\nIo non ho pa[F#m]ura[E][A]\nPerché so che sei con[F#m] me[E][A]\nE perché Tu sei con[F#m] me[E][A]\nChi temerò, [E]chi temer[D]ò\n\n{comment:"CORO:"}\n[A]Tu non mi lascerai mai, anche se la notte è buia\n[F#m]Tu non mi lascerai mai, quando il vento soffia forte\n[E]Tu non mi lascerai mai, non mi lasce[D]rai mai[D][C]\n\n{comment:"BRIDGE:"}\nPosso già vedere una [A]luce che risplende per me\nIl buio fini[F#m]rà e per sempre con Te resterò\n[E]Per adorarti, per a[D]dorarti[D][C]',
    author: "Unknown",
    upload_key: "A",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "e1e47ed1-58ee-42f5-b8dc-431b433972b0",
    created_at: "2024-12-16 14:41:02.187733+00",
    song_title: "Tirami più vicino",
    lyrics:
      '\n{comment:"VERSO:"}\n[F#m]Il tuo amore ha rapito il mio cuore[E]\nSconvolge t[A/C#]utto, sconvolge[D] tutto\n[F#m]La sola c[E]osa che amo è stare\nCon Te per sempre[A/C#], con Te per se[D]mpre\n\n{comment:"CORO:"}\n[A]Tir[E]ami piu vicino\nPortami in profondita[F#m]\nVo[D]glio conoscerti\nVo[A]glio conoscerti\n[A]Per[E]che niente è piu dolce\nDel Tuo amore per me[F#m]\nVo[D]glio conoscerti\nVoglio conosce[Bm]rti[A][D]\n\n{comment:"BRIDGE:"}\n[D]Ooo o[A]oo, qu[E]anto è g[F#m]rande il tuo amore per me\n[D]Ooo o[A]oo, [E]ne ho bisogno adessof[F#m][D]',
    author: "Bethel",
    upload_key: "A",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "e3aa59ff-ffcb-4966-abf4-67d9af20feea",
    created_at: "2024-12-16 15:41:34.407287+00",
    song_title: "Tu sei vivo",
    lyrics:
      "E' il gio[C]rno in cui Ci alziamo [D]e\nGridiam[Bm]o il Tuo nome Di[Em]o\nPor[C]taci al cuore[D] Tuo\n[Bm]Tu sarai se[Em]mpre qui\n\n[C]Col fuoco dentro noi Viviamo e[D]\nL'amo[Bm]re Tuo risplenderà[Em]\n[C]Vedremo la Tua gloria Dio [D]\nNel [Bm]buio Tu luce sarai[Em]\n\n[C]Dio Tu non fallisci mai Il tuo amore r[D]esterà \n[Em]Brillerà dentro me Ogni gi[Bm]orno crescerà\n\n[C]Tu[D] Sei vivo Tu Sei vivo \n[Bm]Den[Em]tro di me per sempre\n\n[C]Per sempre Per sempr[D]e\n[Bm]Per sempre Nel Tu[Em]o amore\n\nlo so che",
    author: "Hillsong",
    upload_key: "C",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "e4e61406-7c29-4aa2-965f-31719ba59d4d",
    created_at: "2024-12-16 10:28:01.987771+00",
    song_title: "Osanna",
    lyrics:
      '\n{comment:"VERSO 1:"}\n[D]Io vedo il re di gloria\n[Bm]sulle nuvole venir \ncon gran poter, con[Em] gran poter[A]\n[D]Nella sua compassione \n[Bm]ha lavato i nostri cuor\nnoi figlio suoi ca[Em]ntiamo a Lui[A]\n\n{comment:"CORO:"}\n[D]Osanna, [G]Osan[A]na[Bm]\n[G]Osanna all[Bm]\'altissimo[A]\n[D]Osanna, [G]Osan[A]na[Bm]\n[G]Osanna all\'al[A]tissimo[D][Bm]\n\n{comment:"VERSO 2:"}\n[D]Vedo una generazione \n[Bm]pronta a servire Te\ncon fede e amor, si al[Em]zerà[A]\n[D]Vedremo il risveglio\n[Bm]Ti preghiamo e ti cerchiam,\nnoi ci prostriam e[Em] a Lui gridiam[A]\n\n{comment:"BRIDGE:"}\n[G]Rendi puro il mio cuor[A]\n[D]Apri i miei occhi a ciò che non [Bm]so\n[G]fammi amare come Tu hai amato m[A]e[Bm]\n[G]Spezza il mio cuore per te[A]\n[D]tutto ciò che sono è per il tuo voler[Bm]\n[G]ora in terra e un dì per [A]l\'eternità[Bm][D]',
    author: "Hillsong",
    upload_key: "D",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "e59bfa13-52eb-4f1c-a947-ab04ae5aecec",
    created_at: "2024-12-15 21:52:55.708797+00",
    song_title: "Gesù tu sei qui - This is a move",
    lyrics:
      "{comment: Verse 1:}\nI monti fai muovere ancor\n[C]E sciogli i legami, Signore\n[D]Dio noi crediamo,\n[Em]Possiamo vedere\n[C]Le meraviglie che fai\n\n{comment: Verse 2:}\nI giganti abbatti ancor,\nI corpi fai risuscitar \nDio noi crediamo, \nPossiamo vedere \nLe meraviglie che fai\n\n{comment: Chorus:}\nSiamo qui per[Em] Te,[C]\nVieni e fai [G]ciò che vuoi, [D]\nSiamo qui per [Em]Te,[C]\nVieni e fai c[G]iò che vuoi,[D]\nI nostri cuori a[Em]priamo, [C]\nVieni e fai ci[G]ò che vuoi [D]\n[C]Gesù Tu sei qui[G]\n\n{comment: Bridge:}\n\nMiraco[C]li accadono fra noi,\nLa tu[Em]a guarigione su di noi,\nMirac[C]oli accadono fra noi,\nI Ci[Em]eli aperti\nGesù Tu sei qui[C][G][Am][G]",
    author: "Tasha Cobbs",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "e6645c56-90f5-43a2-91f6-15628fcfaa91",
    created_at: "2024-12-11 21:34:35.981328+00",
    song_title: "Dio padre nei Cieli",
    lyrics:
      "{comment: Verse 1:}\n[B]Dio padre nei cieli,\n[E]Santo è il nome t[F#]uo\n[B]Che venga il tuo regno\n[E]E la tua volon[F#]tà\n\n{comment: PRE-CORO:}\n[E]Cosi in terra c[C#m]om’è in cie[G#m]lo, in ci[F#]elo\n[E]Cosi in terra c[C#m]om’è in cie[G#m]lo, in ci[F#]elo\n\n\n{comment: Chorus:}\n[E]Venga il tuo regno\nVenga il tuo [G#m]regno[F#]\n\n\n{comment: BRIDGE:}\n[E]Tuo è il regno, tua è la potenza\n[G#m]Tua è la gloria per se[B/D#]mpre amen",
    author: "Bethel",
    upload_key: "B",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "e6ea14c1-bd14-4e95-a3b9-2cd09445be97",
    created_at: "2024-12-16 09:46:13.955821+00",
    song_title: "L'aria sta cambiando - Here as in heaven ",
    lyrics:
      '{comment: "VERSO:"}\n[G] L\'aria sta cambiando [D]\n[G] Lo Spirito di Dio è q[D]ui \n[G] La sua presenza è intorno a noi[D]\n[G] Lo Spirito di Dio è[D] qui\n\n{comment:"CORO:"}\n[G] Riempi tutto in noi il tuo grande amore ci circonda [Bm][A]\n[G] Noi veniamo per Te a cercare il Tuo amore Immenso[Bm][A]\n\n{comment:"BRIDGE:"}\n[G] Vogliamo Te spargi su noi [A][Bm]\nLa Tua presenza[A]\n[G] Sia fatta la tua volontà[A][Bm]\nQui come in cielo[A]\n\n{comment:"VERSO 2:"}\n[G] Un miracolo succederà [D/A]\n[G/B] Lo Spirito di Dio qui[D/A]\n[G] La sua presenza è intorno a noi [D/A]\nG/B                  D/A        (G)\n  Lo Spirito di Dio è qui',
    author: "Elevation Worship",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "e71a5665-644e-4a49-adb5-53e1066922ca",
    created_at: "2024-12-16 12:06:03.10916+00",
    song_title: "Questa è la grazie tua",
    lyrics:
      '\n{comment:"VERSO:"}\n[G]chi vince il buio ed il peccato\n[C]il cui amore è così grande\n[Em]il Re di gloria, Re [D]sopra tutti i r[C]e\n\nchi scuote tutta la terra intera \nchi ci stupisce in ogni istante\nil Re di glora, Re sopra tutti i re \n\n{comment:"CORO:"}\nquesta è la grazia Tu[G]a\nil Tuo infinito amor[C]e\nhai preso il posto [Em]mio\nportato i pesi mi[D]ei\nhai dato la tua vi[G]ta\nperché io fossi libe[C]ro[Em]\nGesù io ca[D]nto\ndi quel che fai per [G]me [C]\n\n{comment:"VERSO 2:"}\n\nchi spazza via la confusione\nchi ci ha resi suoi figli e figlie\nil Re di gloria, Re sopra tutti i re\nchi guida il mondo con la giustizia\nil cui splendore è come il sole\nil Re di gloria, Re sopra tutti I re\n\n{comment:"BRIDGE:"}\n[G]Deg[Em]no è l agnello di Dio \n[C]Degno è il re che ha vinto la morte\n',
    author: "Phill Wickam",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "e7af45bb-9372-4c87-a05a-0460c30f644d",
    created_at: "2024-12-16 12:35:41.437683+00",
    song_title: "Stupenda Grazia - Amazing grace (My chains are gone)",
    lyrics:
      '{comment: "VERSO 1"}\nSt[E]upenda grazia di[A] Gesù[E], salvò perfino me[B]\nl[E]o ero cieco e perso [A]ma chiar[E]ezza ade[B]sso c\'è[A]\n\n{comment:"VERSO 2:"}\nLa grazia sua mi insegnò a confidare in Lui \nDai miei timori mi rialzò, preziosa è per me\n\n{comment:"CORO:"}\nLe mie catene [A]Gesù spezzò[E]\nDal mi[E/G#]o peccato [A]mi liberò[B]\nE s[E/G#]corre in me [A]la grazia sua[C#m]\nDio ha per me [F#m]  im[B]menso amor[E]\n\n{comment:"VERSO 3:"}\nFedele è la parola sua, Dio mi benedirà \nE mi proteggerà perché, dalla mia parte Egli è\n\n{comment:"VERSO 4:"}\nLa Terra un giorno passerà E niente resterà \nMa Dio che mi chiamò quaggiù Sarà sempre con me \nTu sei sempre con me',
    author: "Chris Tomlin",
    upload_key: "E",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "ea8f0166-3cec-4307-adab-2bcc7121fda2",
    created_at: "2024-12-16 14:42:46.674919+00",
    song_title: "Tu lo hai detto",
    lyrics:
      '{comment: "Verso 1"}\n[C]C\'è una promessa che va oltre i miei errori[G]\nC\'è un sussurro che[C] toglie ogni timore[G]\nTutte le imperfe[C]zioni in me[D/F#]\n[G]Son miracoli ancora in corso[C]\nM[G/B]iracoli ancora in corso[D]\n\n{comment:"Coro"}\nCol tuo sangu[C]e vita ho\nCol tuo [G]tocco pieno sarò\nTu lo hai detto e i[C]o so che lo [Em]farai[D][G]\nLa tempesta [C]calmerai\nLa tua mano no[G]n mi lascerà\nTu lo hai det[C]to e io so che lo f[Em]arai[D][G]\n\n{comment:"Verso 2"}\n[C]Ora e sempre Tu non cambierai[G]\nIn ogni momen[C]to Tu operi per me[G]\nGesù tu no, non[C] fallirai[D/F#]\nT[G]u regnerai per sempre[C]\nTu [G/B]regnerai per sempre[D]\n\n{comment:"Bridge"}\nS[C]ia compiuta nei cieli\nLa tu[D]a volontà, Pad[Em]re si compirà[D]\nTu[C]o è il regno per sempre\nLa t[D]ua volontà, Fa[Em]tta sarà[D]',
    author: "Elevation Worship",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "ed073a1a-e905-41a1-9d23-ffc1898b6f3b",
    created_at: "2024-12-16 10:19:23.707158+00",
    song_title: "Mi amerai per sempre",
    lyrics:
      '{comment: "INTRO:"}\n[Em][C][G][D][x][3]\n[C][Em][D][x][2]\n\n{comment:"VERSO:"}\n[Em]Chi ci separer[C]à?\n[G]Anche se io sc[D]appo via\n[Em]Mi amerai per s[C]empre[G][D]\n[Em]Sbaglierò anco[C]ra ma\n[G]La Tua Grazia [D]è sulla vita mia\n[Em]Mi amerai per s[C]empre[G][D]\n\n{comment:"CORO:"}\n[C]Tu sei lo ste[G]sso in eterno\n[D]Il Tuo [Am]Amor non cambia m[C]ai\nDopo la no[G]tte verrà\nLa[D] luce del ma[Am]ttino\n[C]Se l[G]a tempesta po[D]i\nSi abba[Am]tterà su m[C]e\nIo non av[G]rò paura per[D]ché\nMi am[Am]erai per sempre[C][Em][D]\n\n{comment:"VERSO 2:"}\nNelle acque profonde Tu\nRimani fermo sempre accanto a me\nMi amerai per sempre\nLa meta è lontana ma\nCon Te vicino io ce la farò\nMi amerai per sempre\n\n{comment:"BRIDGE:"}\nSo che T[C]u vuoi tu[Em]tto il meglio per m[D]e\nSo che Tu vuoi tutto il meglio per me',
    author: "Jesus Culture",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "f193aaa1-ad5a-4fb7-b5d6-1862c6fff01e",
    created_at: "2024-12-11 21:36:04.450799+00",
    song_title: "Dio vogliamo solo Te",
    lyrics:
      "\n{comment: VERSO 1:}\n[G]Dio vogliamo solo Te\nRiempi i nostri cuo[Em]ri\n[C]Vieni e inondac[G]i\n\n[G]E guidaci a Te\nSpirito di D[Em]io\n[C]Brucia ora q[G]ui\n\n{comment: CORO :}\n[C]Vie[D]ni q[Em]ui\n[C]Soffi[D]a in n[Em]oi\n[C]Noi v[D]ogli[Em]amo Te[D]\n\n{comment: VERSO 2:}\nNoi siamo nella gloria tua Signore\nSapendo che sei qui, Noi siamo liberi\nOh Dio che la nostra lode sia\nIl trono tuo Gesù, Meraviglioso sei\n\n{comment: BRIDGE:}\nVenga il tuo regno[C]\nMuoviti tra noi[Em]\nIn Te la nostra fede[G]\nGrande Dio[D/F#]\n\n\n{comment: BRIDGE 2:}\nNiente è impossibile a Te\nIl tuo regno mai fine avrà\nCrediamo in Te, \nGrande Dio",
    author: NaN,
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "f28085ec-b5a5-4711-b823-46a39f65e162",
    created_at: "2025-03-26 19:17:20.953548+00",
    song_title: "Bontà di Dio // Goodness of God",
    lyrics:
      'LA BONTÀ DI DIO\n{comment:"VERSO 1"}\nTi amo Dio, la t[G]ua Grazia mai mi manca[C][G]\nI giorni m[Em]iei tenuti nelle ma[C]ni tue[D]\nDal momento in cui mi sveglio[Em]\nAl calare dell[G]a ser[D/F#]a[Em]\nIo canterò [C]della tua Bontà[D][G]\n\n{comment:"CORO"}\nN[C]ella mia vita sei fedele[G]\nNella mi[C]a vita sei così buono[G][D]\nN[C]el respiro più profondo[G][D/F#][Em]\nIo canterò[C] della tua Bontà[D][G]\n{comment:"VERSO 2"}\nAmo la tua voce ,Tu mi hai guidato nel deserto\nNelle notti buie sei vicino come nessun altro\nIo ti conosco come Padre,\nMigliore amico mio\nIo canterò della tua Bontà\n\n{comment:"BRIDGE"}\nL[G/B]a tua Bontà mi [C]guarda e corre verso me[D][G]\nL[G/B]a tua Bontà mi [C]guarda e corre verso me[D][G]\nL[G/B]a mia vita ora [C]riposa in Te, Tutto posso[D] arrendere[Em]\nL[G/B]a tua Bontà mi [C]guarda e corre verso me[D][G]',
    author: "Bethel",
    upload_key: "G",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
  {
    id: "fde97222-8157-4624-b2f2-e5c4653527bf",
    created_at: "2024-12-16 09:43:36.439785+00",
    song_title: "Gioia al mattino",
    lyrics:
      '\n{comment:"Coro"}\n[C]Mi hai dato gioia al mattino, gioia la sera\n[G]mi fai danzare in ogni stagione;[Dm]\n[Dm]Qualsiasi cosa\n[F]accadrà gioia ho.[C]\n\n\n{comment:"Verso"}\n[G]Perchè non dovrei cantare le lodi nelle difficoltà[F][C]\n[G]perché non dovrei darti il mio cuore se vedo la tua bon[F]tà.[C]\n\n{comment:"Precoro"}\n[Dm]Non avrò vergogna, io non temerò[Am]\n[C]Ho trovato salvezza in te[G]\n[Dm]cioè che è folle per gli altri,\nper te è libert[Am]à e adesso non mi[C] tratterro[G]\n\n{comment:"Coro"}\n\n\n\n{comment:"Bridge"}\nGioia[C] cè dentro il mio cuore.\n[A#]Gioia cè dentro il mio cuore.\nGi[Am]oia cè dentro il mio cuore.\n\nAllelui[F]a.',
    author: "Martin Smith",
    upload_key: "C",
    artist: NaN,
    album: NaN,
    youtube: NaN,
    spotify: NaN,
    church: "24a8b487-5c81-47c9-8d6c-28fe08a1917c",
  },
];
